* Applying Texture to Canvas in HTML

** Create Canvas Element
   First, create a canvas element in your HTML. Give it an `id` so you can easily reference it in your JavaScript code.
   #+BEGIN_SRC html
   <canvas id="myCanvas" width="400" height="400"></canvas>
   #+END_SRC

** Load Texture Image
   Load the texture image you want to use (e.g., grass or wood) using the `Image` object in JavaScript.
   #+BEGIN_SRC javascript
   const textureImage = new Image();
   textureImage.src = 'path_to_your_texture_image.png';
   #+END_SRC

** Wait for Image to Load
   Before you can use the texture image, you need to wait for it to load completely.
   #+BEGIN_SRC javascript
   textureImage.onload = () => {
     // Call a function to set up the canvas with the texture
     setupCanvasWithTexture(textureImage);
   };
   #+END_SRC

** Set Up Canvas with Texture
   Define a function to set up the canvas with the texture. This involves drawing the texture image onto the canvas.
   #+BEGIN_SRC javascript
   function setupCanvasWithTexture(textureImage) {
     const canvas = document.getElementById('myCanvas');
     const context = canvas.getContext('2d');

     // Draw the texture image onto the canvas
     const texture = context.createPattern(textureImage, 'repeat');
     context.fillStyle = texture;
     context.fillRect(0, 0, canvas.width, canvas.height);

     // You can also draw other shapes or elements on top of the texture
     // For example, draw a rectangle to simulate a textured area
     context.fillStyle = 'rgba(255, 255, 255, 0.5)';
     context.fillRect(50, 50, 300, 300);
   }
   #+END_SRC

** Call the Function
   Finally, call the function to set up the canvas with the texture image when it's loaded.
   #+BEGIN_SRC javascript
   textureImage.onload = () => {
     setupCanvasWithTexture(textureImage);
   };
   #+END_SRC

Replace `'path_to_your_texture_image.png'` with the actual path to your grass or wood texture image.

In this example, the `createPattern` method is used to create a repeating pattern with the texture image. You can adjust the positioning and sizing of the texture to suit your needs. Additionally, you can draw other elements on top of the texture to create more complex compositions.
